### PR TITLE
Feature/add GitHub actions

### PR DESCRIPTION
**Pull request by be-green**

### CODE REVIEW

**Comment by be-green** [comment]
This adds:

- Automated R CMD CHECK on ubuntu, mac, and windows on push
- Adds a simple readme
- Adds some automated tests which check the cv.rq.pen behavior that bracket search was breaking (see `tests/`)

**Comment by be-green** [comment]
To enable the github actions to run you might need to change something under Settings -> Actions -> Allow all github actions, and possibly change "Workflow Permissions" to "Read and write permissions"

**Comment by bssherwood** [comment]
Looks like I had those settings already, but let me know if there are any problems.

**Comment by be-green** [comment]
Looks like it's working to me! You can see how it's going under the "Actions" tab (in case you haven't used this stuff before).

**Pull request merged**
